// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v7.35.0
// source: gateway.proto

package gatewaypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 客户端 -> 网关
type ClientEnvelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*ClientEnvelope_Auth
	//	*ClientEnvelope_Chat
	//	*ClientEnvelope_Stop
	//	*ClientEnvelope_Ping
	Body          isClientEnvelope_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientEnvelope) Reset() {
	*x = ClientEnvelope{}
	mi := &file_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientEnvelope) ProtoMessage() {}

func (x *ClientEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientEnvelope.ProtoReflect.Descriptor instead.
func (*ClientEnvelope) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *ClientEnvelope) GetBody() isClientEnvelope_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *ClientEnvelope) GetAuth() *AuthRequest {
	if x != nil {
		if x, ok := x.Body.(*ClientEnvelope_Auth); ok {
			return x.Auth
		}
	}
	return nil
}

func (x *ClientEnvelope) GetChat() *ChatRequest {
	if x != nil {
		if x, ok := x.Body.(*ClientEnvelope_Chat); ok {
			return x.Chat
		}
	}
	return nil
}

func (x *ClientEnvelope) GetStop() *StopRequest {
	if x != nil {
		if x, ok := x.Body.(*ClientEnvelope_Stop); ok {
			return x.Stop
		}
	}
	return nil
}

func (x *ClientEnvelope) GetPing() *Ping {
	if x != nil {
		if x, ok := x.Body.(*ClientEnvelope_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

type isClientEnvelope_Body interface {
	isClientEnvelope_Body()
}

type ClientEnvelope_Auth struct {
	Auth *AuthRequest `protobuf:"bytes,1,opt,name=auth,proto3,oneof"`
}

type ClientEnvelope_Chat struct {
	Chat *ChatRequest `protobuf:"bytes,2,opt,name=chat,proto3,oneof"`
}

type ClientEnvelope_Stop struct {
	Stop *StopRequest `protobuf:"bytes,3,opt,name=stop,proto3,oneof"`
}

type ClientEnvelope_Ping struct {
	Ping *Ping `protobuf:"bytes,4,opt,name=ping,proto3,oneof"`
}

func (*ClientEnvelope_Auth) isClientEnvelope_Body() {}

func (*ClientEnvelope_Chat) isClientEnvelope_Body() {}

func (*ClientEnvelope_Stop) isClientEnvelope_Body() {}

func (*ClientEnvelope_Ping) isClientEnvelope_Body() {}

type AuthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionToken  string                 `protobuf:"bytes,1,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"` // 游戏登录服下发
	PlayerId      string                 `protobuf:"bytes,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthRequest) Reset() {
	*x = AuthRequest{}
	mi := &file_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthRequest) ProtoMessage() {}

func (x *AuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthRequest.ProtoReflect.Descriptor instead.
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *AuthRequest) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

func (x *AuthRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

type ChatRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RequestId      string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`                                                      // 客户端生成，回包据此归位
	ConversationId string                 `protobuf:"bytes,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`                                       // 空=新会话；通常由网关托管，客户端可不传
	NpcId          string                 `protobuf:"bytes,3,opt,name=npc_id,json=npcId,proto3" json:"npc_id,omitempty"`                                                                  // 对话对象，用于选择 Dify 应用/会话隔离
	Query          string                 `protobuf:"bytes,4,opt,name=query,proto3" json:"query,omitempty"`                                                                               // 玩家输入
	Context        map[string]string      `protobuf:"bytes,5,rep,name=context,proto3" json:"context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 可选：客户端侧附加上下文
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ChatRequest) Reset() {
	*x = ChatRequest{}
	mi := &file_gateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRequest) ProtoMessage() {}

func (x *ChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRequest.ProtoReflect.Descriptor instead.
func (*ChatRequest) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *ChatRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ChatRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *ChatRequest) GetNpcId() string {
	if x != nil {
		return x.NpcId
	}
	return ""
}

func (x *ChatRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *ChatRequest) GetContext() map[string]string {
	if x != nil {
		return x.Context
	}
	return nil
}

type StopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopRequest) Reset() {
	*x = StopRequest{}
	mi := &file_gateway_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRequest) ProtoMessage() {}

func (x *StopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRequest.ProtoReflect.Descriptor instead.
func (*StopRequest) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{3}
}

func (x *StopRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type Ping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_gateway_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{4}
}

// 网关 -> 客户端
type ServerEnvelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*ServerEnvelope_AuthResult
	//	*ServerEnvelope_Chunk
	//	*ServerEnvelope_Done
	//	*ServerEnvelope_Error
	//	*ServerEnvelope_Pong
	//	*ServerEnvelope_Blocked
	Body          isServerEnvelope_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerEnvelope) Reset() {
	*x = ServerEnvelope{}
	mi := &file_gateway_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerEnvelope) ProtoMessage() {}

func (x *ServerEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerEnvelope.ProtoReflect.Descriptor instead.
func (*ServerEnvelope) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{5}
}

func (x *ServerEnvelope) GetBody() isServerEnvelope_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *ServerEnvelope) GetAuthResult() *AuthResult {
	if x != nil {
		if x, ok := x.Body.(*ServerEnvelope_AuthResult); ok {
			return x.AuthResult
		}
	}
	return nil
}

func (x *ServerEnvelope) GetChunk() *ChatChunk {
	if x != nil {
		if x, ok := x.Body.(*ServerEnvelope_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

func (x *ServerEnvelope) GetDone() *ChatDone {
	if x != nil {
		if x, ok := x.Body.(*ServerEnvelope_Done); ok {
			return x.Done
		}
	}
	return nil
}

func (x *ServerEnvelope) GetError() *ErrorMsg {
	if x != nil {
		if x, ok := x.Body.(*ServerEnvelope_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *ServerEnvelope) GetPong() *Pong {
	if x != nil {
		if x, ok := x.Body.(*ServerEnvelope_Pong); ok {
			return x.Pong
		}
	}
	return nil
}

func (x *ServerEnvelope) GetBlocked() *ChatBlocked {
	if x != nil {
		if x, ok := x.Body.(*ServerEnvelope_Blocked); ok {
			return x.Blocked
		}
	}
	return nil
}

type isServerEnvelope_Body interface {
	isServerEnvelope_Body()
}

type ServerEnvelope_AuthResult struct {
	AuthResult *AuthResult `protobuf:"bytes,1,opt,name=auth_result,json=authResult,proto3,oneof"`
}

type ServerEnvelope_Chunk struct {
	Chunk *ChatChunk `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"`
}

type ServerEnvelope_Done struct {
	Done *ChatDone `protobuf:"bytes,3,opt,name=done,proto3,oneof"`
}

type ServerEnvelope_Error struct {
	Error *ErrorMsg `protobuf:"bytes,4,opt,name=error,proto3,oneof"`
}

type ServerEnvelope_Pong struct {
	Pong *Pong `protobuf:"bytes,5,opt,name=pong,proto3,oneof"`
}

type ServerEnvelope_Blocked struct {
	Blocked *ChatBlocked `protobuf:"bytes,6,opt,name=blocked,proto3,oneof"`
}

func (*ServerEnvelope_AuthResult) isServerEnvelope_Body() {}

func (*ServerEnvelope_Chunk) isServerEnvelope_Body() {}

func (*ServerEnvelope_Done) isServerEnvelope_Body() {}

func (*ServerEnvelope_Error) isServerEnvelope_Body() {}

func (*ServerEnvelope_Pong) isServerEnvelope_Body() {}

func (*ServerEnvelope_Blocked) isServerEnvelope_Body() {}

type AuthResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthResult) Reset() {
	*x = AuthResult{}
	mi := &file_gateway_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResult) ProtoMessage() {}

func (x *AuthResult) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResult.ProtoReflect.Descriptor instead.
func (*AuthResult) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{6}
}

func (x *AuthResult) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *AuthResult) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ChatChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Delta         string                 `protobuf:"bytes,2,opt,name=delta,proto3" json:"delta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatChunk) Reset() {
	*x = ChatChunk{}
	mi := &file_gateway_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatChunk) ProtoMessage() {}

func (x *ChatChunk) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatChunk.ProtoReflect.Descriptor instead.
func (*ChatChunk) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{7}
}

func (x *ChatChunk) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ChatChunk) GetDelta() string {
	if x != nil {
		return x.Delta
	}
	return ""
}

type ChatDone struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RequestId      string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ConversationId string                 `protobuf:"bytes,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	TotalTokens    uint32                 `protobuf:"varint,3,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ChatDone) Reset() {
	*x = ChatDone{}
	mi := &file_gateway_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatDone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatDone) ProtoMessage() {}

func (x *ChatDone) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatDone.ProtoReflect.Descriptor instead.
func (*ChatDone) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{8}
}

func (x *ChatDone) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ChatDone) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *ChatDone) GetTotalTokens() uint32 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

type ErrorMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorMsg) Reset() {
	*x = ErrorMsg{}
	mi := &file_gateway_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorMsg) ProtoMessage() {}

func (x *ErrorMsg) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorMsg.ProtoReflect.Descriptor instead.
func (*ErrorMsg) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{9}
}

func (x *ErrorMsg) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ErrorMsg) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ErrorMsg) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 审核命中终止帧：客户端收到后须丢弃该 request_id 已收的全部增量，展示 fallback 文案。
type ChatBlocked struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Fallback      string                 `protobuf:"bytes,2,opt,name=fallback,proto3" json:"fallback,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatBlocked) Reset() {
	*x = ChatBlocked{}
	mi := &file_gateway_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatBlocked) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatBlocked) ProtoMessage() {}

func (x *ChatBlocked) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatBlocked.ProtoReflect.Descriptor instead.
func (*ChatBlocked) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{10}
}

func (x *ChatBlocked) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ChatBlocked) GetFallback() string {
	if x != nil {
		return x.Fallback
	}
	return ""
}

type Pong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pong) Reset() {
	*x = Pong{}
	mi := &file_gateway_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{11}
}

var File_gateway_proto protoreflect.FileDescriptor

const file_gateway_proto_rawDesc = "" +
	"\n" +
	"\rgateway.proto\x12\agateway\"\xc1\x01\n" +
	"\x0eClientEnvelope\x12*\n" +
	"\x04auth\x18\x01 \x01(\v2\x14.gateway.AuthRequestH\x00R\x04auth\x12*\n" +
	"\x04chat\x18\x02 \x01(\v2\x14.gateway.ChatRequestH\x00R\x04chat\x12*\n" +
	"\x04stop\x18\x03 \x01(\v2\x14.gateway.StopRequestH\x00R\x04stop\x12#\n" +
	"\x04ping\x18\x04 \x01(\v2\r.gateway.PingH\x00R\x04pingB\x06\n" +
	"\x04body\"O\n" +
	"\vAuthRequest\x12#\n" +
	"\rsession_token\x18\x01 \x01(\tR\fsessionToken\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\tR\bplayerId\"\xfb\x01\n" +
	"\vChatRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\tR\x0econversationId\x12\x15\n" +
	"\x06npc_id\x18\x03 \x01(\tR\x05npcId\x12\x14\n" +
	"\x05query\x18\x04 \x01(\tR\x05query\x12;\n" +
	"\acontext\x18\x05 \x03(\v2!.gateway.ChatRequest.ContextEntryR\acontext\x1a:\n" +
	"\fContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\",\n" +
	"\vStopRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\"\x06\n" +
	"\x04Ping\"\xa7\x02\n" +
	"\x0eServerEnvelope\x126\n" +
	"\vauth_result\x18\x01 \x01(\v2\x13.gateway.AuthResultH\x00R\n" +
	"authResult\x12*\n" +
	"\x05chunk\x18\x02 \x01(\v2\x12.gateway.ChatChunkH\x00R\x05chunk\x12'\n" +
	"\x04done\x18\x03 \x01(\v2\x11.gateway.ChatDoneH\x00R\x04done\x12)\n" +
	"\x05error\x18\x04 \x01(\v2\x11.gateway.ErrorMsgH\x00R\x05error\x12#\n" +
	"\x04pong\x18\x05 \x01(\v2\r.gateway.PongH\x00R\x04pong\x120\n" +
	"\ablocked\x18\x06 \x01(\v2\x14.gateway.ChatBlockedH\x00R\ablockedB\x06\n" +
	"\x04body\"4\n" +
	"\n" +
	"AuthResult\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"@\n" +
	"\tChatChunk\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x14\n" +
	"\x05delta\x18\x02 \x01(\tR\x05delta\"u\n" +
	"\bChatDone\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\tR\x0econversationId\x12!\n" +
	"\ftotal_tokens\x18\x03 \x01(\rR\vtotalTokens\"W\n" +
	"\bErrorMsg\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"H\n" +
	"\vChatBlocked\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1a\n" +
	"\bfallback\x18\x02 \x01(\tR\bfallback\"\x06\n" +
	"\x04PongB\"Z dify_gateway/api/proto;gatewaypbb\x06proto3"

var (
	file_gateway_proto_rawDescOnce sync.Once
	file_gateway_proto_rawDescData []byte
)

func file_gateway_proto_rawDescGZIP() []byte {
	file_gateway_proto_rawDescOnce.Do(func() {
		file_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gateway_proto_rawDesc), len(file_gateway_proto_rawDesc)))
	})
	return file_gateway_proto_rawDescData
}

var file_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_gateway_proto_goTypes = []any{
	(*ClientEnvelope)(nil), // 0: gateway.ClientEnvelope
	(*AuthRequest)(nil),    // 1: gateway.AuthRequest
	(*ChatRequest)(nil),    // 2: gateway.ChatRequest
	(*StopRequest)(nil),    // 3: gateway.StopRequest
	(*Ping)(nil),           // 4: gateway.Ping
	(*ServerEnvelope)(nil), // 5: gateway.ServerEnvelope
	(*AuthResult)(nil),     // 6: gateway.AuthResult
	(*ChatChunk)(nil),      // 7: gateway.ChatChunk
	(*ChatDone)(nil),       // 8: gateway.ChatDone
	(*ErrorMsg)(nil),       // 9: gateway.ErrorMsg
	(*ChatBlocked)(nil),    // 10: gateway.ChatBlocked
	(*Pong)(nil),           // 11: gateway.Pong
	nil,                    // 12: gateway.ChatRequest.ContextEntry
}
var file_gateway_proto_depIdxs = []int32{
	1,  // 0: gateway.ClientEnvelope.auth:type_name -> gateway.AuthRequest
	2,  // 1: gateway.ClientEnvelope.chat:type_name -> gateway.ChatRequest
	3,  // 2: gateway.ClientEnvelope.stop:type_name -> gateway.StopRequest
	4,  // 3: gateway.ClientEnvelope.ping:type_name -> gateway.Ping
	12, // 4: gateway.ChatRequest.context:type_name -> gateway.ChatRequest.ContextEntry
	6,  // 5: gateway.ServerEnvelope.auth_result:type_name -> gateway.AuthResult
	7,  // 6: gateway.ServerEnvelope.chunk:type_name -> gateway.ChatChunk
	8,  // 7: gateway.ServerEnvelope.done:type_name -> gateway.ChatDone
	9,  // 8: gateway.ServerEnvelope.error:type_name -> gateway.ErrorMsg
	11, // 9: gateway.ServerEnvelope.pong:type_name -> gateway.Pong
	10, // 10: gateway.ServerEnvelope.blocked:type_name -> gateway.ChatBlocked
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_gateway_proto_init() }
func file_gateway_proto_init() {
	if File_gateway_proto != nil {
		return
	}
	file_gateway_proto_msgTypes[0].OneofWrappers = []any{
		(*ClientEnvelope_Auth)(nil),
		(*ClientEnvelope_Chat)(nil),
		(*ClientEnvelope_Stop)(nil),
		(*ClientEnvelope_Ping)(nil),
	}
	file_gateway_proto_msgTypes[5].OneofWrappers = []any{
		(*ServerEnvelope_AuthResult)(nil),
		(*ServerEnvelope_Chunk)(nil),
		(*ServerEnvelope_Done)(nil),
		(*ServerEnvelope_Error)(nil),
		(*ServerEnvelope_Pong)(nil),
		(*ServerEnvelope_Blocked)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gateway_proto_rawDesc), len(file_gateway_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gateway_proto_goTypes,
		DependencyIndexes: file_gateway_proto_depIdxs,
		MessageInfos:      file_gateway_proto_msgTypes,
	}.Build()
	File_gateway_proto = out.File
	file_gateway_proto_goTypes = nil
	file_gateway_proto_depIdxs = nil
}
